name: Sync to private repo

on: [push, pull_request]

env:
  PRIVATE_REPOSITORY_URL: "git@github.com:EpitechPGE45-2025/G-DER-800-PAR-8-1-derogdev801-1.git"

jobs:
  sync:
    if: github.repository == 'AdamBrutsaert/trinity'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to private repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.PRIVATE_REPOSITORY_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
